name: Windows

on:
  release:
    types: [published]

jobs:
  build-project:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Run CMake
        run: |
          dir
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCUSTOMIZE_BUILD=On -DSUPPORT_FILEFORMAT_SVG=On -G "Unix Makefiles" ..
          make
          cd ..

      - name: Zip artifacts
        run: |
          mv build/*.exe .
          rm -r build/*
          mv *.exe build/
          7z a windows.zip build/ assets/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ./windows.zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'release' && github.event.action == 'published'
